% Read random data generated by BatRandom
% and evaluate randomness and frequency
% ----------------------------------------
% filename to look for
FileName = "RandomData.txt";
% Parameters for frequency check
Fs = 625000; % Abtastfrequenz 
NoS = 10000; % Number of samples to shown

% -------------- Code ------------
% Load the data from file; the data was generated by testbench
y = load ("-ascii", FileName);
%y = wavread("TPDF.wav");
%y = wavread("Test24.wav");

%{
z = (y*(2**23));
y_int = int32(z);
y_int = y_int/256;
y = double(y_int);
y = y/32768;
%}

%Fourier Transform of Sound File 
Nsamps = length(y); 
t = (1/Fs)*(1:Nsamps);          %Prepare time data for plot 

%Do Fourier Transform 
y_fft = abs(fft(y));            %Retain Magnitude 
y_fft = y_fft(1:Nsamps/2);      %Discard Half of Points 
f = Fs*(0:Nsamps/2-1)/Nsamps;   %Prepare freq data for plot 

%Plot Sound File in Time Domain 
fig = figure(1);    %
plot(t, y);
xlim([0 NoS*(1/Fs)])  
xlabel('Time (s)') 
ylabel('Amplitude') 
title('File'); 

%Plot the data for checking the randomness
fig = figure(fig+1);    % first figure shows randomness
plot(y, ".");
xlabel('Samples') 
ylabel('Amplitude') 
title('Randomness'); 
% print -dpng "Rand.png";

%Plot Sound File in Frequency Domain 
fig = figure(fig+1);    %
plot(f, y_fft);
%ylim([0 5])  
xlim([0 Fs/2]) 
xlabel('Frequency (Hz)') 
ylabel('Amplitude') 
title('Frequency Response');


