% Read random data generated by BatRandom
% and evaluate randomness and frequency
% ----------------------------------------
% filename to look for
FileName = "Data45KHz";
WavName = [FileName ".wav"];
TxtName = [FileName ".txt"];
% -------------- Code ------------
% Load the data from file; the data was generated by testbench
y = wavread(WavName);
z = (y*(2**23));
y_int = int32(z);
save("-ascii", TxtName, "y_int");



