% Read random data generated by BatRandom
% and evaluate randomness and frequency
% ----------------------------------------
% filename to look for
FileName = "OutSound";
WavName = [FileName ".wav"];
TxtName = [FileName ".txt"];
OutPutBits = 16;
OutPutBR = 625000;
% -------------- Code ------------

% Load the data from output file of test bench
y = load ("-ascii", TxtName);
y = y/(2**(OutPutBits-1));  % scale output
% write data back to wav file
wavwrite(y, OutPutBR, OutPutBits, WavName);


