% Read random data generated by BatRandom
% and evaluate randomness and frequency
% ----------------------------------------
% filename to look for
OrgFileName = "Data45KHz.txt";
DitheredFileName = "Dithered.txt";

% Parameters for frequency check
Fs = 625000; % Abtastfrequenz 

% -------------- Code ------------
fig = 0;
% Load the data from files
% Original data from sound file
y = load ("-ascii", OrgFileName);
y = y/(2**23);                  % this file has 24 bits resolution
% Dithered data from testbench
z = load ("-ascii", DitheredFileName);
z = z/(2**15);                  % this file has 16 bits resolution

%Fourier Transform of Sound File 
Nsamps = length(y); 
t = (1/Fs)*(1:Nsamps);          %Prepare time data for plot 
f = Fs*(0:Nsamps/2-1)/Nsamps;   %Prepare freq data for plot 

%Do Fourier Transform for original file
y_fft = abs(fft(y));            %Retain Magnitude 
y_fft = y_fft(1:Nsamps/2);      %Discard Half of Points 
%Do Fourier Transform for dithered file
z_fft = abs(fft(z));            %Retain Magnitude 
z_fft = z_fft(1:Nsamps/2);      %Discard Half of Points 

% write data back to wav file
wavwrite(z, 625000, 8, "Output.wav");

%Plot Sound File in Time Domain 
%fig = figure(fig+1);    %
%plot(t, y);
%xlim([0 Nsamps*(1/Fs)])  
%xlabel('Time (s)') 
%ylabel('Amplitude') 
%title('Original File'); 

%Plot Sound File in Time Domain 
%fig = figure(fig+1);    %
%plot(t, z);
%xlim([0 Nsamps*(1/Fs)])  
%xlabel('Time (s)') 
%ylabel('Amplitude') 
%title('Dithered File'); 

%Plot Original Sound File in Frequency Domain 
figure();    %
plot(f, z_fft, "r", f, y_fft, "b");
ylim([0 0.1])  
xlim([0 Fs/2]) 
xlabel('Frequency (Hz)') 
ylabel('Amplitude') 
title('Frequency Response Dither TPDF  24->16 Bits');
% print -dpng Res.png

%Plot dithered Sound File in Frequency Domain 
%fig = figure(fig+1);    %
%plot(f, z_fft,"r");
%ylim([0 0.001])  
%xlim([0 Fs/2]) 
%xlabel('Frequency (Hz)') 
%ylabel('Amplitude') 
%title('Frequency Response Dithered (16 Bits)');

